services:
  huajibot:
    image: ghcr.io/nbtca/huaji-bot-dotnet:latest
    container_name: huajibot
    environment:
      TZ: "${TZ:-Asia/Shanghai}"
    volumes:
      - ./data:/app/data
    network_mode: host
    restart: unless-stopped
